### ISSUE TITLE
Describe iOS state of development

### ISSUE THREAD

**Issue by alsms** [iPlug2/iPlug2#102]
This project contains code fragments targeting iOS and the examples also contain XCode iOS projects. However, no example yet exists that contains a fully working iOS version, because some of the fundamental source files are still missing in the current state of the repository (such as "IPlug/AUv3" directory). 

Could you please describe the current progress of implementing iOS as a build target in the documentation?

**Comment by olilarkin** [comment]
iOS is working well with some more work to do to support serializing/unserializing state and platform features such as multi-touch, text entry, sandbox-safe file storage. I have not yet decided on the license for the AUv3 code or had time to release anything myself using it, which is why i haven't made it public yet. If you have experience with iOS and would like to help me finalise it (and avoid any license restrictions i might put on it, please let me know - i am quite busy and could do with some help)

**Comment by olilarkin** [comment]
closing this for now.
