### ISSUE TITLE
certain keys filtered in mac standalone app

### ISSUE THREAD

**Issue by olilarkin** [iPlug2/iPlug2#108]
return/esc and more do not get to IGraphics_view. Need to fix for custom text entries

for ref
https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/EventOverview/HandlingKeyEvents/HandlingKeyEvents.html#//apple_ref/doc/uid/10000060i-CH7-SW11

**Comment by AlexHarker** [comment]
This all happens at the level of the swell app main.

We do have the opportunity to bypass default window processing by adding SWELLAPP_PROCESSMESSAGE to the app and then returning that we've dealt with the message.

**Comment by AlexHarker** [comment]
To clarify - seen that there was SWELLAPP_PROCESSMESSAGE handling, but it's been disabled - not sure why that was.

As the disabled code is right now the filtered keys will be processed both by the view's keyDown method, and then the SWELL app default processing. This is because the swell app method return s 0. If after processing it was to return a non-zero value then default processing wouldn't happen - is this a viable solution?

**Comment by olilarkin** [comment]
I disabled it because it wasn’t working with the ns text field ,  causing a alert sound when pressing return

**Comment by olilarkin** [comment]
well done, fixed on master
