### ISSUE TITLE
WAM examples throw exception when browser zoom != 100%

### ISSUE THREAD

**Issue by olilarkin** [iPlug2/iPlug2#122]
refresh page with zoom != 100% = exception

**Comment by AlexHarker** [comment]
Depends on the size - this appears to be an issue with bitmaps where the scale is beneath 50% - I suspect we need a minimum scale of 1 for finding images.

**Comment by AlexHarker** [comment]
Will also depend on the screen resolution. On a retina this will happen under 50%. On non-retina anything under 100%.

I've fixed it on master, but the issue stems from devicePixelRatio (retrieved in OpenWindow()) incorporating the zoom amount. We should decide how this should work, because right now different bitmaps will be loaded according to the zoom on open, but zooming after loading won't change the bitmaps.
