### ISSUE TITLE
Externalize general content from plug in sources  

### ISSUE THREAD

**Issue by alexliesenfeld** [iPlug2/iPlug2#150]
It is recommended to create a new plug-in project by duplicating exiting example plugins. These, however, do come with a number of scripts and other dependencies that evolve over time, as development on iPlug 2 moves on. 

Hence additional effort is needed to maintain iPlug2 plugins because bug fixes and other improvements do not automatically mirror in the duplicates and must be replayed manually in every plug-in project, which is error prone and very tedious. 

For maintainability reasons, it is necessary to externalize all resources from the plug-in sources, so that only user content is contained inside an iPlug project and general files, such as build scripts, installers, build settings, etc. should be externalized and be kept in a place that can benefit from updates in the iPlug repository.

**Comment by olilarkin** [comment]
I am aware of this pain point. I didn't mean to change the project format much after initial release in January for that exact reason, but then I started working on CI/CD and realised there were of course issues with the build/installer scripts that needed to be updated for iplug2

Once things have stabilised, it should be less of an issue, but still things could be improved as follows:

- could make a project generator like the projucer.
- could do something with cmake.
- make "out of source" builds easier via the project duplicator

I really could do with someone stepping up to help with either of those things.

**Comment by aimxhaisse** [comment]
Not sure if this is something that was explored, what about shipping iPlug2 as a library & includes, like the way deps are provided?

That way doing something from the outside wouldn't depend on a specific build system, nor on iPlug2 maintaining support for different build systems, it would also make Linux support easier. Making a simple makefile that just links with it would work well, scripts could be shipped in a bin directory.

I'm a bit sad that to use a cool framework, you need to convert to use tools you aren't necessarily familiar with (xcode, etc) ; when those would work well as well with a lib/include/bin structure.

**Comment by olilarkin** [comment]
We did think about making a libIPlug.a or libIGraphics.a at some point but that would now require some major refactoring and would generate a huge amount of work, so it wont happen, sorry.

it's impossible to cater for everyone's preferences, but i hope we can have existing setup + cmake support for a bit more flexibility at some point.

FWIW, using XCode on macOS/iOS is somewhat needed in order to support all the code signing stuff, bundle packaging, interface builder stuff... it would be far more weird and time consuming to do something different.

I am really happy with the setup we have and so not very inclined to change it

**Comment by aimxhaisse** [comment]
Makes sense, thanks for the detailed answer!

**Comment by olilarkin** [comment]
iPlug2OOS is the recommend way to manage an iPlug2 project out of source

https://github.com/iPlug2/iPlug2OOS
