### ISSUE TITLE
Unable to detect arrow keys

### ISSUE THREAD

**Issue by tommitytom** [iPlug2/iPlug2#211]
OnKeyDown and OnKeyUp do not seem to react to the arrow keys. Is there a way to enable them?

**Comment by olilarkin** [comment]
You need to be more specific about which platform/format you are testing with. bY the way  we have a Slack channel where you can discuss stuff before posting an issue

**Comment by AlexHarker** [comment]
I have a Mac app of a plug-in in which I receive arrow keys just fine, so as @olilarkin says - we need more info on what you are building on what platform. Can you also confirm that you are receiving other keys, as it is possible that you are testing a custom control that doesn't have the correct override - without more info it's very hard to be more helpful.

**Comment by tommitytom** [comment]
Sorry to be so vague!  I'm testing on Windows, both as a standalone app, and in VST2/3.  I am receiving other keys (such as standard alpha characters etc), though I am not receiving modifiers either (like ctrl etc)

**Comment by AlexHarker** [comment]
Thanks - this is a windows-specific bug which I can reproduce. The issue is that there is a test to see if the key can be converted to ascii and if the return length of the conversion is not 1 then the key code stops running.

[ @olilarkin - the line if (len == 1) around 402 in IGraphicsWin.cpp is the issue - can you take a look? ]

In terms of modifiers you won't see the modifier key downs as events - you only receive them alongside other keys that are pressed when modifiers are down - this appears to already be working correctly.

**Comment by tommitytom** [comment]
I see this is fixed on master now :)  I also receive the VK_CONTROL as a keypress too (which I actually have a use case for).  Thanks!

**Comment by AlexHarker** [comment]
Cool - thank @ddf - he was the one who put the fix in!
