### ISSUE TITLE
IGraphicsSkia::PathArc not working in some circumstances

### ISSUE THREAD

**Issue by olilarkin** [iPlug2/iPlug2#295]
With CPU and METAL, an IVSliderControl with default round handle looks like this:

![Screenshot 2019-09-03 at 12 03 03](https://user-images.githubusercontent.com/655662/64168531-a6ea1480-ce43-11e9-96cf-0e123d274e19.png)

possibly bug here https://github.com/iPlug2/iPlug2/blob/master/IGraphics/Drawing/IGraphicsSkia.cpp#L415

**Comment by AlexHarker** [comment]
I'll try to take a look - I wonder if this is related to the memory leak...
BTW - I think the skit build we have is not necessarily targeting earlier Mac OSes...

**Comment by AlexHarker** [comment]
Not an arc issue, but a transform issue. Also not metal related (which doesn't work on my computer - I think the build is wrong for my OS).

The issue is that this is drawn as an ellipse which involves transforms, as transforms are not applied to the path, but to the canvas, so the transform sin this case never get applied. The model Graphics follows is one where as the path gets altered transforms apply, whereas skia seems to favour singular applications of transforms after gathering a path together - the solution is to figure ou how to get the behaviour we need under that model.

**Comment by AlexHarker** [comment]
This is an attempt to address it.

https://github.com/iPlug2/iPlug2/tree/graphics-skia-transforms

**Comment by olilarkin** [comment]
Seems to work - happy to merge it? I renamed to https://github.com/iPlug2/iPlug2/tree/graphics/skia-transforms

**Comment by AlexHarker** [comment]
Yeah - sorry - old naming still in my head. Please merge - it is better than before and if we discover any further errors we can fix them up at that stage.

**Comment by AlexHarker** [comment]
I deleted the branch as I see no need to keep it.
