### ISSUE TITLE
OnParamChangeUI implementation?

### ISSUE THREAD

**Issue by earlevel** [iPlug2/iPlug2#326]
OnParamChangeUI appears to have an empty implementation, though it's used several places, so it seems superfluous at this point.

`virtual void OnParamChangeUI(int paramIdx, EParamSource source = kUnknown) {};`

Maybe there are plans for it and it's a place holder, but here's one place it's used that seems to defy its purpose as explained in the header file comment:

OnParamChangeUI is defined as "an OnParamChange that will only trigger on the UI thread at low priority, and therefore is appropriate for hiding or showing elements of the UI." It seems odd then that OnParamReset explicitly calls both OnParamChange and OnParamChangeUI, as evident in the header comment and implementation:
```
  /** Calls OnParamChange() and OnParamChangeUI() for each parameter.
   * @param source Specifies the source of the parameter changes */
  void OnParamReset(EParamSource source);
...
void IPluginBase::OnParamReset(EParamSource source)
{
  for (int i = 0; i < NParams(); ++i)
  {
    OnParamChange(i, source);
    OnParamChangeUI(i, source);
  }
}
```
Either I misunderstand that the only difference is use with thread priority, or it's being misused here.

**Comment by AlexHarker** [comment]
This is not superfluous - it's to be provided by the plugin (and hence is virtual) if the plugin needs to do something to the UI when a parameter changes.

There is possibly something to look at here in terms of threading assumptions (which are in any case hard to reason about in the context of an unknown host), so I'll leave this open for @olilarkin to look at that also.

**Comment by earlevel** [comment]
Yes, but do you understand what I'm saying about the description? Your comment, "if the plugin needs to do something to the UI when a parameter changes" seems to agree with its use in OnParamReset, but not with its purpose as described (where it's "an OnParamChange that will only trigger on the UI thread").

To be clear, I'm not saying the implementation is wrong, it may be the description that's lacking. To me the description says it does the same thing (but safer level). But maybe, instead, its a UI-related function that is a companion to OnParamChange as needed. I think its most likely a problem with the description, but I wanted to bring it up in case it might be getting put in the code for different reasons in different places. Obviously not an issue with the current empty implementation, but when its not I would hope it works as expected by the plugin developer.

(The "seems superfluous" comment was meant to refer to the use in OnParamReset. According to the description of OnParamChangeUI, it's the same as OnParamChange but on a different thread level, hence it seems superfluous to do it twice. Of course, if that were true its default implementation would probably be to call OnParamChange. That's why I think it's probably the description that's wrong.)

**Comment by AlexHarker** [comment]
I think I didn't quite follow your meaning in the first post, but I think the basic situation is still the same - I'll try to clarify below.

OnParamChange is not guaranteed to be called on the audio thread (could be called on low priority). I don't off the top of my head know which threads OnParamReset is called from - hence my decision to leave this open to discuss threads, rather than simply closing it. 

OnParamChange UI It is intended for updating UI things, rather than processor things and this also has some relevance if your plugin is distributed (processor and GUI are compiled separately). The call in the reset is correct and not superfluous.

Possibly the description could be improved (although I don't consider it incorrect), but in brief whenever a parameter changes you should expect a call on both methods, and use one to update processor things and the other to update UI things. It has the same function (to tell you that the parameter has updated) but you should respond to it differently.

**Comment by olilarkin** [comment]
As alex says, the reason for two methods is mainly to do with distributed plugins (Web Audio Modules/VST3 distributed) and for clearer plug-in implementation. Typically in iPlug1, i have seen people update DSP as well as Hiding/Showing controls etc in OnParamChange(). Without OnParamChangeUI() we could make people do two OnParamChange() methods with #if IPLUG_DSP / IPLUG_EDITOR guards, or they could put guards inside switch statements but that would be very verbose & confusing.

I am not totally happy with OnParamChangeUI() as a method name (because it is not necessarily UI but really main thread).

I don't think OnParamReset() should ever get called on the audio thread in any plugin API.

closing this
