### ISSUE TITLE
May we have virtual OnParamReset?

### ISSUE THREAD

**Issue by earlevel** [iPlug2/iPlug2#327]
Please make OnParamReset in IPlug/IPlugEditorDelegate.h virtual. OnParamReset is called only when restoring state, and there are cases where a plugin might want special handling when restoring state.

**Comment by AlexHarker** [comment]
It looks like it is used by init functions, and state restoring and also by the faust stuff if the code is recompiled. I can see a potential case for this, but there's also the issue of methods where one must 'call super' in general and whether we should rework to avoid this, as it tends to lead to the possibility of error (and then confusion).

A discussion with @olilarkin would be helpful at figuring out what we'd prefer, as simply putting a virtual on it might not be the best way (and would certainly at least need documenting to ensure the base implementation is called, as otherwise the plug doesn't get the parameter changes).

**Comment by earlevel** [comment]
Understood. However its unlikely anyone will override OnParamReset without knowing what they are doing. And those who need it may just end up editing IPlug2 and adding the virtual keyword. Also, if you need to override OnParamReset, you probably aren't interested in calling super, you want to replace the behavior. If a plugin has functionality that depends on the order of parameters, you don't want to always iterate parameters in order when restoring a preset, it will leave the plugin in a different state than saved.

Of course, if you expect to add other functionality to OnParamReset in the future, that would be a consideration, but if you make it virtual now then you'd probably add that functionality in a different place in the future.

**Comment by olilarkin** [comment]
IEditorDelegate::OnRestoreState() is what you want
