### ISSUE TITLE
IControl members need work - bitset or flags?

### ISSUE THREAD

**Issue by olilarkin** [iPlug2/iPlug2#332]
The IControl base class has a bunch of member variables and setters/getters that could be better dealt with using a bitset and flags.

```
  /** Specify whether the control should respond to mouse overs when grayed out
   * @param allow \c true if it should respond to mouse overs when grayed out (false by default) */
  void SetMOWhenGrayed(bool allow) { mMOWhenGrayed = allow; }

  /** Specify whether the control should respond to other mouse events when grayed out
   * @param allow \c true if it should respond to other mouse events when grayed out (false by default) */
  void SetMEWhenGrayed(bool allow) { mMEWhenGrayed = allow; }

  /** @return \c true if the control responds to mouse overs when grayed out */
  bool GetMOWhenGrayed() const { return mMOWhenGrayed; }

  /** @return \c true if the control responds to other mouse events when grayed out */
  bool GetMEWhenGrayed() const { return mMEWhenGrayed; }
  
  /** @return \c true if the control ignores mouse events */
  bool GetIgnoreMouse() const { return mIgnoreMouse; }```

**Comment by AlexHarker** [comment]
How many of these do you want to put in a bitfield? There are a lot of bools in the IControl structure.

Unfortunately these are currently protected, so likely changing this will be breaking for some plugins.

**Comment by olilarkin** [comment]
yeah, i think it would be much nicer though

these are the ones i think should be flags:

  bool mDisablePrompt = true;
  bool mDblAsSingleClick = false;
  bool mMOWhenGrayed = false;
  bool mMEWhenGrayed = false;
  bool mIgnoreMouse = false;
  bool mWantsMidi = false;

**Comment by gvampgh** [comment]
BTW, MO and ME are not very intuitive. Flags would be nice, but please leave the getter :-)

**Comment by AlexHarker** [comment]
OK - so the plan is to make sure *all* of these have getters and setters, but internally they are dealt with by flags @olilarkin - is that correct? I'm happy to look at this but I'd rather agree a spec so as to do it once.

If you agree with the above the work is:

- rework the internal field to be *private* int
- provide getters/setters for all
- look at naming (including ray/disabled from #333 
- replace all direct access in IControls

Is that right?

**Comment by olilarkin** [comment]
no, just GetFlag/SetFlag i think.

**Comment by AlexHarker** [comment]
OK - so:

- public glas
- rework a private int flag field.
- provide getflgs/setflags
- replace all direct access in IControls
- replace all calls to access flags elsewhere

**Comment by olilarkin** [comment]
yes that sounds like what is needed!

**Comment by AlexHarker** [comment]
Untested, but I believe this is correct enough to review:

https://github.com/iPlug2/iPlug2/tree/graphics/icontrols-bitfield

We needed SetFlags() / AddFlags() / RemoveFlags()

I've also given GetFlags() and GetFlag() for ease.

**Comment by gvampgh** [comment]
I had a short look.

a) completely removing the getter/setter is no good idea imao, since the new Set and Get methods just deal with ints (whats again not very intuitive). EFlags should be at least referred in the method help. On the other hand it would be ok, if you use bitsets or Flag data types/templates itself, how it is done here:
https://stackoverflow.com/questions/1448396/how-to-use-enums-as-flags-in-c

b) please rename these to either "Disable" or append the "Disabled" to the end.
    kFlagDisabledMouseOver      = 0x4,
    kFlagDisabledMouseEvents    = 0x8,  

Thx

**Comment by AlexHarker** [comment]
a -You are correct that the documentation could be improved. However, if I use an enum type it implies that you can only set one at a time (that they are mutually exclusive) - that is not the case - the system here is the same as in IParam for flags - I copied the style exactly for consistency - whatever is used should be consistent with IParam as it is a similar flag system. You will note that I use an enum type for GetFlag() which deals with a single flag only. It is worth noting, however that Param has individual getters for all the flags which is a difference - I was going on what was agreed with @olilarkin  above.

b -I did not name them disable, because that would imply that they disable things - they don't do that - they set whether you receive mouse overs or other events *when the control is disabled* - hence the choice of name.

**Comment by olilarkin** [comment]
I've decided the bitfield is too much of a breaking change. In this PR I've renamed some of the cryptic methods/variables

https://github.com/iPlug2/iPlug2/pull/352
