### ISSUE TITLE
SetDirty() causes secondly opened plugin window to go black when first plugin window is closed 

### ISSUE THREAD

**Issue by janhase88** [iPlug2/iPlug2#350]
i tested this with bitwig and reaper, nanovg, winx64 vst3
to reproduce:
implement OnIdle in IPlugEffect and call SetallControlsDirty():
```
void IPlugEffect::OnIdle() {
  GetUI()->SetAllControlsDirty();
}
```
open two instances of Iplugeffect in a daw (in reaper on two different tracks) 
open one after another. close the firstly opened one - the secondly openend one should go black.
doesnt happen when SetAllControlsDirty is not implemented. does also happen, when SetDirty() is called in a custom Icontrol from Draw() function.

![2019-10-14-12-58-37](https://user-images.githubusercontent.com/46456607/66746813-29beb000-ee83-11e9-8256-d84d3d4f1d96.gif)

**Comment by baktery** [comment]
Same issue here: winx64, VST2 + Ableton Live

**Comment by AlexHarker** [comment]
Thanks for the report - can you confirm what drawing backends you are using, and whether changing this (say to Cairo or skia) still results in the same issue?

Ta.

**Comment by AlexHarker** [comment]
This looks like an OpenGL bug (it appears with NanoVG, but it's possible it would arise with other GL environments).

I'm concerned that it is this:
https://www.khronos.org/opengl/wiki/Common_Mistakes#The_Object_Oriented_Language_Problem

When I debug I see that glGenTextures twice returns the same "names" for textures that should be independent between plug-ins - thus, when items get deleted from one plug the other one gets broken. I *think* this is because we are loading resources before we have a valid context (due to where resource loading happens in plug2 - it is possible we can avoid this somehow, but this is the source of the bug - refactoring to load after the context is available would be very tedious and the context may later change, so I'm wondering if a temporary valid context might do the same job?

**Comment by AlexHarker** [comment]
OK - looks like this might something a bit different as we have valid contexts on windows, so I'm wondering if called gladLoadGL() each time, might be related.

**Comment by AlexHarker** [comment]
And - it looks like actually we weren't setting the relevant openGL context as current when deleting things - I have a PR that I believe fixes this, but I'm wondering if we need to also review this on Mac? @olilarkin - might need a hand with that.

**Comment by AlexHarker** [comment]
Right - this is fixed on windows and Mac!
