### ISSUE TITLE
LoadBitmap, use of targetScale

### ISSUE THREAD

**Issue by TBProAudio** [iPlug2/iPlug2#354]
Not really an issue, more a question:

Can some please explain the use of LoadBitmap/targetScale and image@2x.png?
Currently I have "image.png" and "image@2x.png", but "image@2x.png" is not used if GUI is scaled to 2x.

Thank you.

**Comment by olilarkin** [comment]
Not the right place for questions

**Comment by AlexHarker** [comment]
Can you clarify if you mean that the screen scale is 2x, or that you have changed the *draw* scale. If the latter then I think this is expected behaviour, but I'd have to check

**Comment by TBProAudio** [comment]
Thanks for your attention :-)
I use `const IBitmap bIMAGE_FN = pGraphics->LoadBitmap(IMAGE_FN, 1, false, 2);`
together with a simple bitmap control. 2 variants of images are available: "image.png" and "image@2x.png".
If GUI is scaled from 50% to 200% only "image.png" is used and correctly up/down scaled. 
1) I wonder now what the use of "image@2x.png" is. It seems to be touched as well, but not drawn. I could expect that GUI scale 50% to 150% uses "image.png" and 150% to 200% uses "image@2x.png". But maybe I´m wrong here :-(
2) I try to find out what to to if only "image@2x.png" should be used during GUI scales from 50% to 200% (so only downscaling).

So currently I cannot say if there is bug or feature...

**Comment by AlexHarker** [comment]
There are two kinds of scaling. ScreenScale is used for hi-res displays (e.g. retina on Mac). Draw scaling changes how big the display is to the user (and can be any scale). You seem to be changing the draw scale.

I've checked and currently we only use the @x2 images for hi-res displays, not when the display scale is changed. There is no bug I can see. In this case because you load at a target scale of 2 the x2 image will be loaded from disk, but then because the display is at 1x (I assume) the controls will reload the bitmap at x1. Does that make it clearer?

**Comment by TBProAudio** [comment]
Thank you, this makes sense.
