### ISSUE TITLE
Removing "using namespace Steinberg;" statements from the global namespace

### ISSUE THREAD

**Issue by satellitnorden** [iPlug2/iPlug2#366]
This causes many compilation issues for me as I am trying to use some math libraries to develop plugins that clashes with some declarations in that library. Using statements at the global level is more often than not less than ideal and should be removed. (:

**Comment by AlexHarker** [comment]
I agree. This needs to be done in headers only (the cpps are fine, because there are no clashes at present).

It's quite a bit of work, though, and we'd appreciate any help that you'd be able to offer in terms of tackling some of the headers and making PRs. I think we'd accept any PRs that did this, subject only to suitable (consistent) style. Thanks.

**Comment by olilarkin** [comment]
https://github.com/iPlug2/iPlug2/pull/369

**Comment by olilarkin** [comment]
merged
