### ISSUE TITLE
Lice/Windows DrawText/DoDrawText resets mDrawRECT

### ISSUE THREAD

**Issue by gvampgh** [iPlug2/iPlug2#373]
This is hard to explain and I encounter it in my own framework, but is an IPlug2 issue (was ok with same coding in IPlug 1 and debugged it), I try to describe:

In a custom control i first draw a text with above methods. Then I draw a FillRect. In DrawText / NeedClipping of Lice implementation UpdateLayer is called, and there mDrawRECT is overwritten with reduced/optimized rect from coordinate 0,0.
A following FillRect in Lice takes this "wrong" mDrawRECT in the first line and is not able to draw it at the right position:
IRECT r = TransformRECT(bounds).Intersect(mDrawRECT.GetScaled(GetScreenScale()))

I hope this is understandable, seems that one of the methods needs an update.

**Comment by AlexHarker** [comment]
Would you be able to provide the code for the custom control, or ideally a cut down version? Thanks.

**Comment by gvampgh** [comment]
Hi @AlexHarker , yes, please have a look at my branch https://github.com/gvampgh/iPlug2/tree/recterr
This is just a small change in IPlugEffect using Lice. With default gfx engine everything is ok. When switching FillRect and DrawText it's also ok. But as coded it's faulty in lice.

**Comment by AlexHarker** [comment]
This is not an issue with mDrawRECT. This gets updated correctly because a clipping layer is being created for the drawing to be correctly clipped (in this case when you draw text). Unfortunately, when you draw to the clipping layer with an additive blend the background is not on the clipping layer and you get this result.

Probably the correct solution is to copy the background through to the clipping layer when it is created, although this will add cost.

**Comment by AlexHarker** [comment]
Fixed in ac6d190473c9286eb501dba29b2d37c00c2670d0 by copying the background contents onto the clipping layer.
