### ISSUE TITLE
add Built-in "viewport"  functionality

### ISSUE THREAD

**Issue by olilarkin** [iPlug2/iPlug2#41]
From the JUCE documentation: 

*A Viewport is used to contain a larger child component, and allows the child to be automatically scrolled around.

To use a Viewport, just create one and set the component that goes inside it using the setViewedComponent() method. When the child component changes size, the Viewport will adjust its scrollbars accordingly.*

I think I plug should have something like this, which is particularly useful for scrolling areas on mobile

**Comment by AlexHarker** [comment]
There are a few options:

1 - an IGraphics within an IGraphics (probably has lots of extra unneeded stuff
2 - a specific new class that IGraphics knows about IViewPort
3 - an Control that hosts other controls.

Transforms are easy to deal with for path classes or maybe layers (the latter would allow for LICE - otherwise LICE won't be supported)

**Comment by AlexHarker** [comment]
The Control option is possibly easier (easiest?) once multiple parameter controls are a thing.

**Comment by olilarkin** [comment]
closing, track issue on #590
