### ISSUE TITLE
Improve behavior of PathArc

### ISSUE THREAD

**Issue by pressplay123** [iPlug2/iPlug2#431]
**Describe the bug**
For path based drawing, I tend to define a full path first before calling `PathStroke` exactly once at the end. Assume, I want to draw two independent arcs. If I would do the following there would be an unwanted connecting line between the first and second arc:

**To Reproduce**

```
graphics.PathArc(x, y, radius, angleStart, angleEnd);
graphics.PathArc(x, y, 2 * radius, angleStart, angleEnd);
graphics.PathStroke(COLOR_RED, 1);
```

**Expected behaviour**
Two independent arcs are drawn, one at `radius` and one at `2 * radius`. Nothing more, nothing less.

**IMPORTANT DETAILS**
IGRAPHICS_BACKEND == ALL. At least I have checked skia and cairo.

**How to fix for IGRAPHICS_SKIA**
[like this](https://github.com/iPlug2/iPlug2/pull/419/commits/1963d50474f99dca682427c6f599f7e1e71bcfbd
)

**Additional context**
`PathRoundRect` and all other functions which rely on the old behavior would have to be adapted by manually calling `PathLineTo` where necessary. Watch for multiple consecutive calls to `PathArc`.

**Comment by AlexHarker** [comment]
Thanks for taking the time to explain the issues you are having.

Unfortunately, the behaviour you are seeing is the expected behaviour for IGraphics as based on most graphics libraries I am familiar with. I've just run a test on an html canvas and I don't get two separate arcs - I get a line joining them (and that's why I the skia method would be set to extend the path and not add). Cairo works the same (see https://www.cairographics.org/samples/rounded_rectangle/) and I'm pretty sure nanovg and skia would do the same with native calls although I haven't explicitly tested.

The normal way of achieving what you want to do (and using a single stroke) would be one of the following:

- call PathClose() before the second arc
- call PathMoveTo() before the second arc (more complex because you need to know where to move to)

Hopefully that gives you a way to achieve what you want.

**Comment by pressplay123** [comment]
This is not consistent though, because `PathLine` and `PathRadialLine` for instance behave differently - there is no implicit connection between independent paths. But of course, if this is the standard way, I'm fine with it. As a result, I will call `PathStroke` two times in such situations.

**Comment by AlexHarker** [comment]
The implementation of PathLine() starts with a PathMoveTo() call which leads to the difference of behaviour. In any case the functionality of PathArc() needs to be somewhere as it is - I agree that the fact that the shapes add closed paths and the arc does not might be confusing - I'll chat it over with Oli and see if we can make this clearer at all.

To clarify you don't need to call PathStroke twice (although I think it might be more efficient to do so).

You can call.

PathArc()
PathClose()
PathArc()
PathStroke()
