### ISSUE TITLE
IControls not redrawn properly when moving a IControl

### ISSUE THREAD

**Issue by baktery** [iPlug2/iPlug2#487]
**Describe the bug**
When setting a new position of a IControl some controls are not properly redrawn.

**To Reproduce**
Test case here:
https://github.com/baktery/iPlug2/tree/issue_redraw_control_setposition/Examples/SetPositionIssue

First, execute without any change and check how the control is moving and redraw is done properly. This is the expected behaviour.

Then, to reproduce the issue, uncomment the SetAllControlsDirty() call:

https://github.com/baktery/iPlug2/blob/3541a015d16fa5f51ccbb17817fa60273e1151f2/Examples/SetPositionIssue/SetPositionIssue.cpp#L59

**Expected behaviour**
Controls are properly redrawn and no SetAllControlsDirty() call is needed.

Reproduced on windows 10 as standalone app using NanoVG.

**Comment by olilarkin** [comment]
This is a genuine issue.

here is a potential way we could fix this. Prior to updating the control position we could push the existing bounds of the control to be added to the dirty region list.

      GetUI()->PushDirtyRegion(pControl->GetRECT());
      pControl->SetPosition(newx, newy);

@AlexHarker what do you think about this?

diff --git a/IGraphics/IGraphics.h b/IGraphics/IGraphics.h
index 2125af42a4e7883d90a2046065d6dfee7296be78..a0a62f583b1d337effd062825839306b2a11acfb 100644
--- a/IGraphics/IGraphics.h
+++ b/IGraphics/IGraphics.h
@@ -1491,6 +1491,11 @@ public:
   /** Remove all gesture recognizers linked to regions */
   void ClearGestureRegions();
 
+  void PushDirtyRegion(const IRECT& r)
+  {
+    mExtraDirtyRegions.Add(r);
+  }
+
 protected:
 
   /** /todo
@@ -1608,6 +1613,7 @@ private:
 
   int mIdleTicks = 0;
   
+  IRECTList mExtraDirtyRegions;
   std::vector<EGestureType> mRegisteredGestures; // All the types of gesture registered with the graphics context
   IRECTList mGestureRegions; // Rectangular regions linked to gestures (excluding IControls)
   std::unordered_map<int, IGestureFunc> mGestureRegionFuncs; // Map of gesture region index to gesture function
diff --git a/IGraphics/IGraphics.cpp b/IGraphics/IGraphics.cpp
index 5f39a31f7018ef6e7ea14344581fdeb5d80f4a5c..6517517b01794a8cb04a03f3f078a50313b01496 100644
--- a/IGraphics/IGraphics.cpp
+++ b/IGraphics/IGraphics.cpp
@@ -746,6 +746,17 @@ bool IGraphics::IsDirty(IRECTList& rects)
     return true;
   }
 #endif
+  
+  if(mExtraDirtyRegions.Size())
+  {
+    for(int i =0; i <mExtraDirtyRegions.Size();i++)
+    {
+      rects.Add(mExtraDirtyRegions.Get(i));
+    }
+    
+    mExtraDirtyRegions.Clear();
+    dirty = true;
+  }
 
   return dirty;
 }

**Comment by olilarkin** [comment]
[pushdirtyregion.txt](https://github.com/iPlug2/iPlug2/files/4441299/pushdirtyregion.txt)

**Comment by olilarkin** [comment]
I was actually wondering about changing the way we loop though all controls to check if they are dirty, to an approach where each control adds to a "dirty rects" stack if necessary

**Comment by baktery** [comment]
if you didn't take it into account: remember to add the dirty rect when a control is destroyed

**Comment by olilarkin** [comment]
currently set all controls dirty when removing a control

here is a branch where i am working on a solution, although it might not be great for animating control bounds, since many rects may get pushed onto extra dirty rects stack

https://github.com/iPlug2/iPlug2/tree/graphics/move_control_detritus

**Comment by baktery** [comment]
cool! if you need anything from my side let me know it

**Comment by AlexHarker** [comment]
Yes - at the moment if I move controls I set the whole interface dirty. That isn't ideal, but the idea of moving controls is not properly built in. I'll be honest, I'd rather not rewrite the main drawing loop if it can be avoided (because it was quite a bit of work and what is there now functions in cases other than this one, which is an edge case).

The problem here is how to do this to reduce burden on a developer. Of course we can add a dirty region or something for this, but really when you moved something it would all just happen, without needing to either make two calls, or to call a super/utility method in SetPosition().

Perhaps the solution is to add calls to IGraphics that take care of the dirtying where you specifiy the control you want (by tag I presume) and the params? That way you'd just call those methods and IGraphics would do the rest, with nothing to be done per control, where I imagine it would get a bit tedious.

**Comment by AlexHarker** [comment]
I've made a branch with some helpers for doing this. In this model you call IGraphics helpers, rather than directly resizing or repositioning controls. For now that sets all controls as dirty, but if we do modify the drawing mechanisms to allow dirty rects to be set, then this could be optimised in future.

https://github.com/iPlug2/iPlug2/tree/graphics/position-size-helpers

@olilarkin - thoughts? If this works can I merge and close this?

**Comment by olilarkin** [comment]
merged that branch, going to close this. May look at a more efficient solution at a later date
