### ISSUE TITLE
Tooltips don't work when GUI is resized > 1

### ISSUE THREAD

**Issue by cristianvogel** [iPlug2/iPlug2#600]
I have my tooltips working fine, but if my GUI is resized greater than the default , they don't pop up anymore. Seems that scaling below 1 ( shrinking ) , they still work. 

OS X Catalina, XCode.

**Comment by AlexHarker** [comment]
This was a Mac only bug - and should be fixed now on master in 05871ea7c32c5cb0dfaa2eae3b74429167c6a2fa. I don't think it would have worked in either direction fully before, but the layout of your UI might have mean it appeared to work correctly.

Can you pull and confirm that this is now fixed, so that I can close?

**Comment by cristianvogel** [comment]
OK, sorry I missed this notification. I will test now...

**Comment by cristianvogel** [comment]
yes seems fine now

**Comment by AlexHarker** [comment]
Thanks!
