### ISSUE TITLE
ScreenScale has no effect on layers

### ISSUE THREAD

**Issue by pthvogt** [iPlug2/iPlug2#716]
If one put some graphic operation in a layer like this:
```
void test(IGraphics& g)
{
  g.StartLayer(this, mRECT);
      
  // draw some stuff on g

  mLayer = g.EndLayer();
  g.DrawLayer(mLayer);
}
```
the ScreenScale is not used for the drawn stuff.

This can be clearly seen in IGraphicsTest->DropShadow. I've append two screenshots to demonstrate this, one with scale 
100%:
![Screenshot 2021-03-25 153924](https://user-images.githubusercontent.com/26294449/112493258-4bafa800-8d82-11eb-829a-1d7336257987.png)

...and one with scale 125%:
![Screenshot 2021-03-25 153843](https://user-images.githubusercontent.com/26294449/112493369-62ee9580-8d82-11eb-9c8b-a268e9fabf51.png)

Interestingly the shadow is worse: It seemed to by scaled the wrong direction?!

**Comment by AlexHarker** [comment]
I don't think the issue is that it isn't used - I think this is an issue with non integer screen scales. Can you check at 200%? I think that will work.

When I designed the layer stuff it was strictly for integer screen scales only, and only recently did @olilarkin update so that non integer scales would work on windows. That's a good development, but it will mean rethinking layers a bit I expect.

**Comment by AlexHarker** [comment]
Work that needs to be done to enable this:

1 - APIBitmap needs to be allowed to have float scales
2 - all uses of GetRoundedScreenScale() need checking

Sadly this is a bit complex, but I will try to tackle it soonish. This bug should affect windows only.

**Comment by olilarkin** [comment]
The IGraphicsTest does behave correct @200%. This problem was expected, should have made an issue before to track it, Thanks for the report.
