### ISSUE TITLE
OnMouseOut being called although control was entered (Mac)

### ISSUE THREAD

**Issue by pressplay123** [iPlug2/iPlug2#757]
**Describe the bug**
A mouse up event triggers a `OnMouseOut` although the mouse is within the control area.

**To Reproduce**
1. drag a control
2. while dragging, leave the control area
3. still dragging, enter the control area again
4. release the mouse

**Expected behaviour**
`OnMouseOut` is not called upon `OnMouseUp`.

**Comment by AlexHarker** [comment]
I totally agree on the expected behaviour, but now I look I see that mMouseOutDuringDrag is set to false in mouseEntered. On my OS (High Sierra) this appears to give the correct behaviour in the app version, but I've only tested it there. In order to fix this fully I suspect we need to better understand the factors that come into play. Any more info you can give would be appreciated.
