### ISSUE TITLE
Unexisting files?

### ISSUE THREAD

**Issue by FarayMecatronico** [iPlug2/iPlug2#760]
Hi 

The messages on the attached file are displayed when I try to build and run the Example Instrument (IPlugInstrument.xcworkspace).

Apparently there's a missing file...
<img width="456" alt="Screen Shot 2021-06-18 at 5 15 24 PM" src="https://user-images.githubusercontent.com/86110763/122590543-9e36f280-d059-11eb-84e3-424073ca695b.png">
<img width="740" alt="Screen Shot 2021-06-18 at 5 19 01 PM" src="https://user-images.githubusercontent.com/86110763/122590549-a000b600-d059-11eb-8ae3-ed84f14e0916.png">
<img width="456" alt="Screen Shot 2021-06-18 at 5 15 24 PM" src="https://user-images.githubusercontent.com/86110763/122590599-b27aef80-d059-11eb-997e-be41c07d0b40.png">

On the other hand for the signing issue I have already an developer account but it seems it is not accepting it for some reason .

Any suggestion?

**Comment by olilarkin** [comment]
The AAX library is missing if you didn't install the AAX sdk. You only need the AAX sdk if you want to build protools plugins.

You will have to change the "Team" in codesigning settings to your apple developer account Team. You may also need to make sure the bundle has a different ID... i am not certain of this yet since I can't test myself
