### ISSUE TITLE
Check static-storage thread safety

### ISSUE THREAD

**Issue by olilarkin** [iPlug2/iPlug2#81]
Mutexes were removed but possibly shouldn't have been

**Comment by AlexHarker** [comment]
The problem here is that the mutex needs to be held for the duration of a calling method (not just while we call a single method of static storage) to ensure that the object state is consistent.

One way to do that is to rewrite so that the methods can only be accessed indirectly through an accessor class which uses RAII semantics on the mutex. That would mean that it would be impossible to use the storage without the mutex, and impossible to hold on to it by accident.

Do you want me to do that?

**Comment by AlexHarker** [comment]
Yes - it needs to be a level up.

I've put this on the static-storage branch. Whilst I'm here Clear() looks broken and there is a question about the hash we use - I'm not so bothered about the has either way, but it'd be good to fix these up.

**Comment by AlexHarker** [comment]
Looks like for std::hash we'd need to use a std::string. This could be a temporary in the call to Hash(), but we can't hash the C-string directly.

**Comment by AlexHarker** [comment]
Fixed up in 0da90223671856f0904d747a6f4bdea8248e47ff
