### ISSUE TITLE
AUv2, VST3 the sidechain does not work when set 4-4 channels

### ISSUE THREAD

**Issue by wcrhlo** [iPlug2/iPlug2#856]
I apologize in advance for the meager description, but the facts are described in the topic along with the photo. I think this is a separate bug.

First - https://github.com/iPlug2/iPlug2/issues/846

Second:

Type plugin: compressor
Configuration for Reaper (only) works fine (AUv2, VST3  the sidechain does not work when setting 4-4 channels):

```
#define PLUG_CHANNEL_IO "\
1-1 \
1.1-1 \
1.2-1 \
2.1-2 \
2-2 \
2.2-2 \
4-4 \
4.1-4 \
4.2-4"
```

Place this config in a compressor with a side chain. Compile the plugin in AU v2 and VST3 format. Turn on the side chain, or select 4 channels in the Reaper.

**Comment by wcrhlo** [comment]
@AlexHarker 

I'm sorry to distract you for nothing. If you specify a channel greater than 2, the sidechain stops working. Please confirm if this is a bug. Thanks

**Comment by wcrhlo** [comment]
>2 channels sc stop worhing

**Comment by olilarkin** [comment]
4-4 means no sidechain, so I'm not surprised if it doesn't work!

#define PLUG_CHANNEL_IO "\
1-1 \
1.1-1 \
1.2-1 \
2.1-2 \
2-2 \
2.2-2

should be enough to support up to two busses input buses that are either mono or stereo, and one output bus that is mono or stereo

**Comment by wcrhlo** [comment]
I've done the tests and there are a couple of questions. As you can see, I'm not calling you by tag as you asked.

IPlugSideChain
```
void IPlugSideChain::ProcessBlock(sample** inputs, sample** outputs, int nFrames)
{
  const double gain = GetParam(kGain)->DBToAmp();
  const int nChans = NOutChansConnected();
  for (int i=0; i < 4; i++) {
    bool connected = IsChannelConnected(ERoute::kInput, i);
    if(connected != mInputChansConnected[i]) {
      mInputChansConnected[i] = connected;
      mSendUpdate = true;
    }
  }
  
  for (int i=0; i < 2; i++) {
    bool connected = IsChannelConnected(ERoute::kOutput, i);
    if(connected != mOutputChansConnected[i]) {
      mOutputChansConnected[i] = connected;
      mSendUpdate = true;
    }
  }
  
  for (int s = 0; s < nFrames; s++) {
    for (int c = 0; c < nChans; c++) {
      outputs[c][s] = inputs[c][s] * gain;
    }
  }
```


My
```
void PLUGIN::ProcessBlock(sample** inputs, sample** outputs, int nFrames)
{
    double* in1 = inputs[0];
    double* in2 = inputs[1];
    double* in3 = (IsChannelConnected(ERoute::kInput, 2) ? inputs[2] : inputs[0]);
    double* in4 = (IsChannelConnected(ERoute::kInput, 3) ? inputs[3] : inputs[1]);
    double* out1 = outputs[0];
    double* out2 = outputs[1];
```

The fact is that when I switch the number from 2 channels to 4. I get the sound but not the processed sound until I turn it on the 3/4 channel. (1/2 + 3/4). Could you when you have less anger for the "calling you" will answer why is this happening?

**Comment by olilarkin** [comment]
I don't have anger, it's just pointless, since I see all these things anyway

I'll look into your issue  when/if I have time. I don't find what you have written above is very clear... so it requires that I spend more time to try and work out what you mean. Are you still setting a channel IO of 4-4 for example?

FYI: I have sponsorship tiers if you want me to prioritise your issues

**Comment by wcrhlo** [comment]
I use this config and it works great for me:

#define PLUG_CHANNEL_IO "
1-1
1.1-1
1.2-1
2.1-2
2-2
2.2-2

The strangeness is this, I load the plug-in on 2 channels, everything works fine, as soon as I switch to 4 channels in the router card, the original sound starts playing, but as soon as I turn on 3 and 4 channels in the routing card, I hear the processed signal:

![Screenshot 2022-03-20 at 14 15 28](https://user-images.githubusercontent.com/101744616/159164091-d77ebd9d-3983-4d73-ba5c-69db392238cc.png)

After that, I switch back to 2 channels and it works correctly only under such conditions:

![Screenshot 2022-03-20 at 14 17 37](https://user-images.githubusercontent.com/101744616/159164143-3060218b-3c93-4ed3-9fa3-56da07576354.png)

But initially, it worked well on such settings:

![Screenshot 2022-03-20 at 14 18 33](https://user-images.githubusercontent.com/101744616/159164180-f89ce969-2b2c-4a73-93b0-27f26dee6c8a.png)

But if you restart the plugin, it works well on the initial settings until you specify 4 channels for it. We spent a whole week analyzing the IPlugSideChain project and did not find what the problem was (before bothering you). We will think about donates, but at this moment in time when there is a war, we cannot waste money. Thanks.

**Comment by olilarkin** [comment]
i'm going to ignore your comment about the war and "wasting money" since, frankly, it has nothing to do with IPlug2

Nevertheless I tried to reproduce issues with iPlugSideChain VST3 in the latest Reaper, and switching track channel counts, and everything appears to work fine here, so I'd probably need a video to demonstrate the problem at this stage.

**Comment by wcrhlo** [comment]
https://user-images.githubusercontent.com/101744616/159171460-9ce953a1-6d91-4005-97f1-57099abb520d.mov

**Comment by andivax** [comment]
It's definitely bug.
Please take a look @ video:
https://drive.google.com/file/d/1bjIvOIxtaCWnVRdh2tIwc9KlfLoGEN4B/view?usp=sharing

**Comment by olilarkin** [comment]
I can't reproduce the behaviour in your video with the latest Reaper/iPlug2 and IPlugSideChain example. Does IPlugSideChain have the same problem for you?

**Comment by andivax** [comment]
> I can't reproduce the behaviour in your video with the latest Reaper/iPlug2 and IPlugSideChain example. Does IPlugSideChain have the same problem for you?

Sorry Oli, I am not developer, just beta tester. Do you try this on Mac or PC?
I am on PC
Win 10 21H2 x64 Pro

Thank you for fast feedback!

**Comment by wcrhlo** [comment]
I sent you invited to the repo. Basically, there are the main files, but you can ask me for more files if you need them!

**Comment by wcrhlo** [comment]
Current code: https://vimeo.com/manage/videos/690672544

**Comment by AlexHarker** [comment]
OK - here's the bit where you connect input channels:

```double* in1 = inputs[0];
    double* in2 = inputs[1];
    double* in3 = (IsChannelConnected(ERoute::kInput, 2) ? inputs[2] : inputs[0]);
    double* in4 = (IsChannelConnected(ERoute::kInput, 3) ? inputs[3] : inputs[1]);```

I'm unclear on what you are expecting Reaper to do when you set the track to 4-4. As far as I can see you now have inputs 2/3 (counting from zero) connected, so in3 and in4 will use them. But the audio on your track is stereo so they get sent zeros. Therefore your side chain has no input and there is no compression.

That would be what I expect to happen - am I missing something?

**Comment by AlexHarker** [comment]
In general I also don't see how the plugin supports all the formats listed above - it seems to me built to work either in stereo (no side chain) or stereo with a sidechain, and you would need additional code to deal with any other setup as far as I can see.

**Comment by wcrhlo** [comment]
```
    double* in1 = inputs[0]; - L
    double* in2 = inputs[1]; - R
    double* in3 = inputs[2]; - scL 
    double* in4 = inputs[3]; - scR
```

I'm unclear on what you are expecting Reaper to do when you set the track to 4-4. - I expect him to use in1/2 as the default but not in 3/4. 


In general, I also don't see how the plugin supports all the formats listed above - it seems to be built to work either in stereo (no side chain) or stereo with a stereo sidechain (there isn't a correct check for mono sidechain), and you would need additional code to deal with any mono setup (mono sidechain/mono inputs) as far as I can see.

#define PLUG_CHANNEL_IO 

```
1-1  - mono -> mono
1.1-1 - mono + sc mono -> mono
1.2-1 - mono + sc stereo -> mono
2.1-2 - stereo + sc mono -> stereo
2-2 - stereo -> stereo
2.2-2 - stereo + sc stereo -> stereo
```

 ```
if ((IsChannelConnected(ERoute::kInput, 2)))
                {
                    ...sidechain(in1, in3);
                    ....sidechain(in2e, in4);
                }
                else {
                    compression(in1);
                    compression(in2);
                }
```

I rewrote it but the result is the same. If I don't understand something, please explain it in more detail. Thanks

**Comment by wcrhlo** [comment]
Etalon:

https://user-images.githubusercontent.com/101744616/159377134-6e82e9d8-94cc-4b65-b3ef-8a11d70e2295.mov

**Comment by AlexHarker** [comment]
It's very hard to comment on a third party plugin (the glue compressor) for which I don't know how it functions or exactly what it does, but I briefly looked at the manual and as far as I can see the glue compressor has an external side chain button. I expect that if you engage it (turn it on) it will do exactly the same as your plugin. Therefore, the comparison is not like for like.

In your plugin if there are 4 input channels on the track it will use 3 and 4 as the side chain (equivalent to having the external side chain button on in the glue compressor). If the track in Reaper is stereo then by default the routing will send nothing to channels 3 and 4 and therefore there is no compression. In the IPlugSideChain reaper test session you should be able to see that audio is being sent from another track to the side chain.

At the moment it seems that you are convinced that the sidechain is not working, when in fact the issue seems to me to be quite the opposite. The side chain *is working* but you are sending nothing to it. This problem (so far) has nothing to do with code, but rather is about understanding how channel routing in Reaper works. The default routing for a channel with 4 inputs in reaper is to take channels 3 and 4 from inputs 3 and 4 - if the file is stereo that means there is no input to these channels. If you want the behaviour of the glue compressor, you will need to add an external sidechain button to your design. I suspect that other DAWs have a different mechanism for side chains that means that your plugin detects there are being no side chain in  line with your expectations, but Reaper tends to opt for quite explicit routings.

It may be that other DAWs appear to work in other modes, but the code doesn't appear to be correct. As a simple example, you always write to two outputs but if you are on a mono track then you aren't guaranteed to have two outputs to write to. It might be that iplug is providing scratch buffers (and hence this ends up as safe) but there are certainly some configs relating to the input where it seems likely that you may be looking at the wrong input. As I'm not so familiar with side chains I'd have to test my assumptions here to be 100% sure, but at a absolute minimum you are doing more work for mono IO than you need, as you always process a stereo signal.

**Comment by AlexHarker** [comment]
I have just installed the glue compressor and if I put it on a 4 channel track and turn the external side chain on in the interface then I get no compression (as predicted above and as I would have expected).

**Comment by wcrhlo** [comment]
It turns out this is a normal state, and we will have to turn on the sidechain mode + sidechain mode in other hosts, so that everything worked in the Reaper with the sidechain state turned off. Oh, my God. Thank you for explaining this is some kind of horror.

Sorry for the time spent. I apologise!

**Comment by AlexHarker** [comment]
No problem - glad to be able to point you in the right direction.
