### ISSUE TITLE
Unexpected (and undesirable) change in mouse behaviour

### ISSUE THREAD

**Issue by heebje** [iPlug2/iPlug2#902]
Hi,

I've noticed an unexpected (and undesirable) change in behaviour when left-click-dragging control knobs.

It used to be the case that, when left-click-dragging, the mouse would disappear, the control would react, and upon release, the mouse would reappear IN THE SAME SPOT where it was clicked.

Now suddenly, upon release, the mouse reappears IN A DIFFERENT SPOT than where it was clicked, namely corresponding to the actual mouse movement.

This is undesirable and makes operating the knobs uncomfortable.

Was this changed by design, or has a bug crept in?
If it was changed by design, how can I reinstate the old behaviour?

Many thanks,

Matthijs

N.B.: Tried with new, freshly cloned iPlug2, using a fresh duplicate of IPlugEffect, no changes made.
System: Windows 11, 64 bit.
Bug affects both app and vst3 (on Reaper).

**Comment by heebje** [comment]
![mouse_behaviour](https://user-images.githubusercontent.com/16598068/192124422-5ea7d5b2-cbcb-4c29-bca1-e6ffd83dd9f6.gif)

**Comment by AdamSBx** [comment]
A few months ago, I had the same problem with one of my custom controls after updating to the latest version of IPlug2.

According to the notes I made because I was planning to report this, IGraphics::MoveMouseCursor()
which is also used by the Knob class in IPlug2 stopped working (on Windows) after this commit [ff62709](https://github.com/iPlug2/iPlug2/commit/ff62709591dcc29c7b8c52533ebf2e15b388b6e7)

After I undid the changes from this commit, it worked again.

**Comment by AlexHarker** [comment]
IPlug2 aims to detect tablet or touch input and not move the cursor when it is present. The changes referenced came from a PR that was aiming to improve the detection of that, but it looks like the added half of the test might be returning incorrectly on some systems.

The relevant PR was https://github.com/iPlug2/iPlug2/pull/550

@olilarkin - do we need to look in more detail at this?

**Comment by olilarkin** [comment]
Seems so!

**Comment by olilarkin** [comment]
reverted the offending commit on master
