### ISSUE TITLE
VST2/3 crash in BitwigStudio after turning AudioEngine back on when buffersize > 1024 

### ISSUE THREAD

**Issue by janhase88** [iPlug2/iPlug2#96]
hi guys,

In BitwigStudio(in Windows 10), there is the function to turn off the AudioEngine (its decoupled from the GUI, so when it crashes you can reload the Engine without having to restart the whole program).
So when I insert IPlugEffect VST 2/3 in a new Track and then turn off the AudioEngine and back on IPLugEffect crashes****But only if the buffersize is set 2048 samples, when its 1536 it works sometimes, when the buffersize is 1024 samples or below it works everytime. (Steinberg UR22mkII)

in IPlugUtilities.h(Line 134):

Unhandled exception thrown: write access violation.
**pDest** was nullptr. occurred

in IPlugUtilities.h

template <class SRC, class DEST>
void CastCopy(DEST* pDest, SRC* pSrc, int n)
{
for (int i = 0; i < n; ++i, ++pDest, ++pSrc)
{
*pDest = (DEST) *pSrc; <=======((((*HERE))))
}
}

*you can get a demo(no project saving) of bitwig to test it here:
https://www.bitwig.com/en/download.html

**To Turn of AudioEngine in Bitwig:
Right click on the DSP symbol (small blue CPU symbol) next to the BPM (Upper left Corner) to get AudioEngine menu: Deactivate for this Project / Terminate Process

**Comment by olilarkin** [comment]
which plug-in format? VST2 or VST3?

**Comment by AlexHarker** [comment]
Doesn't seem to happen on Mac.

**Comment by AlexHarker** [comment]
OK - so it looks like Bitwig is telling us that the block size is about to be zero and hence we resize all the scratch buffers to doer (null pointers) and then it send us samples. It's hard to debug because the process spawns when audio goes on and then it crashes immediately (no time to attach). Therefore, I'm reliant on asserting where I think there might be an issue.

So I can confirm that I get a block size of zero and also (presumably after that) a call to AttachBuffers with more frames than the last call to set block size.

Seems like a Bitwig bug, but @olilarkin might have ideas about how we should handle this kind of buggy host behaviour.

**Comment by janhase88** [comment]
i cant reproduce this issue anymore. it seems that it was fixed somewhere along the way.
